import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { format } from 'prettier';

const root = path.resolve(import.meta.dirname, '..');
const source = path.resolve(root, process.argv[2] || '../VEGETA-components-v2-core');
const read = (name) => JSON.parse(fs.readFileSync(path.join(source, name), 'utf8'));
const tokens = read('tokens.json');
const spec = read('components.json');
const audit = read('AUDIT.json');
if (spec.families.length !== audit.families.length)
  throw new Error('Family coverage mismatch');
for (const f of audit.families) {
  const actual = spec.families.find((n) => n.id === f.id);
  if (!actual || (actual.variants?.length ?? 0) !== f.variantCount)
    throw new Error(`Variant coverage mismatch: ${f.name}`);
}
for (const [name, hash] of Object.entries(audit.sha256)) {
  if (
    crypto
      .createHash('sha256')
      .update(fs.readFileSync(path.join(source, name)))
      .digest('hex') !== hash
  )
    throw new Error(`Integrity: ${name}`);
}
const variables = Object.fromEntries(tokens.variables.map((v) => [v.id, v.name]));
const palette = Object.fromEntries(
  Object.entries(tokens.color).filter(([k]) => k.startsWith('palette/'))
);
for (const v of Object.values(tokens.color))
  if (typeof v === 'string' && !Object.values(palette).includes(v))
    palette[`palette/${v.slice(1)}`] = v;
// Unbound paints exist in the Illustration master; keep them distinct from the official palette.
const masterPaints = {};
const masterTypography = {};
function collect(n) {
  if (
    n.type === 'TEXT' &&
    n.lineHeight?.unit === 'PIXELS' &&
    tokens.typography[`line-height/${n.lineHeight.value}`] === undefined
  )
    masterTypography[`line-height/${n.lineHeight.value}`] = n.lineHeight.value;
  for (const p of [...(n.fills || []), ...(n.strokes || [])])
    if (p.hex && !Object.values(palette).includes(p.hex))
      masterPaints[p.hex.slice(1)] = p.hex;
  for (const c of n.children || []) collect(c);
}
for (const f of spec.families) for (const n of f.variants || [f.master]) collect(n);
let output = `// Generated by scripts/sync-design.mjs from the audited v2 masters.\nimport type { DesignNode } from './designTypes';\nexport const palette = ${JSON.stringify(palette, null, 2)} as const;\nexport const semantic = {\n`;
for (const [k, v] of Object.entries(tokens.color).filter(
  ([k]) => !k.startsWith('palette/')
))
  output += `  '${k}': ${typeof v === 'string' ? `palette['palette/${v.slice(1)}']` : v},\n`;
output += `} as const;\nexport const globalTokens = ${JSON.stringify({ spacing: tokens.spacing, radius: tokens.radius, typography: tokens.typography }, null, 2)} as const;\n`;
output += `export const masterPaints = ${JSON.stringify(masterPaints, null, 2)} as const;\n`;
output += `export const masterTypography = ${JSON.stringify(masterTypography, null, 2)} as const;\n`;
output += `export const fontNames = { Regular: 'Montserrat_Regular', Medium: 'Montserrat_Medium', SemiBold: 'Montserrat_SemiBold', Bold: 'Montserrat_Bold', Italic: 'Montserrat_Regular_Italic' } as const;\n`;
const buttonHeight = spec.families.find((f) => f.name.startsWith('Button /'))
  .variants[0].height;
const inputHeight = spec.families
  .find((f) => f.name.startsWith('Input /'))
  .variants[0].children.find((n) => n.name === 'Input surface').height;
output += `export const controlMetrics = { buttonHeight: ${buttonHeight}, inputHeight: ${inputHeight} } as const;\n`;
const paint = (p) => {
  if (!p || p.visible === false) return undefined;
  const name = variables[p.boundVariables?.color?.id];
  const key =
    name && typeof tokens.color[name] === 'string'
      ? name
      : Object.values(palette).includes(p.hex)
        ? `palette/${p.hex.slice(1)}`
        : `master/${p.hex.slice(1)}`;
  if (p.opacity !== undefined && p.opacity !== 1) {
    const rgb = p.hex
      .slice(1)
      .match(/../g)
      .map((h) => parseInt(h, 16));
    return `rgba(${rgb.join(',')},${p.opacity})`;
  }
  return `TOKEN:${key}`;
};
const align = {
  MIN: 'flex-start',
  MAX: 'flex-end',
  CENTER: 'center',
  SPACE_BETWEEN: 'space-between',
};
function node(n) {
  const style = { opacity: n.opacity ?? 1 };
  if (n.type === 'TEXT') {
    Object.assign(style, {
      color: paint(n.fills?.[0]),
      fontFamily: `FONT:${n.fontName?.style || 'Regular'}`,
      fontSize:
        tokens.typography[`size/${n.fontSize}`] !== undefined
          ? `TYPE:size/${n.fontSize}`
          : n.fontSize,
      lineHeight:
        n.lineHeight?.unit === 'PIXELS'
          ? tokens.typography[`line-height/${n.lineHeight.value}`] !== undefined
            ? `TYPE:line-height/${n.lineHeight.value}`
            : `MASTER_TYPE:line-height/${n.lineHeight.value}`
          : undefined,
      letterSpacing:
        n.letterSpacing?.unit === 'PERCENT'
          ? (n.fontSize * n.letterSpacing.value) / 100
          : n.letterSpacing?.value,
      includeFontPadding: false,
      textAlign: n.textAlignHorizontal?.toLowerCase(),
    });
  } else {
    Object.assign(style, {
      backgroundColor: paint(n.fills?.[0]),
      borderColor: paint(n.strokes?.[0]),
      borderWidth: n.strokes?.some((p) => p.visible !== false) ? n.strokeWeight : 0,
      borderRadius: n.type === 'ELLIPSE' ? n.width / 2 : n.cornerRadius,
      flexDirection: n.layoutMode === 'VERTICAL' ? 'column' : 'row',
      justifyContent: align[n.primaryAxisAlignItems],
      alignItems: align[n.counterAxisAlignItems],
      paddingTop: n.paddingTop,
      paddingRight: n.paddingRight,
      paddingBottom: n.paddingBottom,
      paddingLeft: n.paddingLeft,
      gap: n.itemSpacing,
    });
    const e = n.effects?.find((e) => e.visible && e.type === 'DROP_SHADOW');
    if (e)
      Object.assign(style, {
        boxShadow: [
          {
            offsetX: e.offset.x,
            offsetY: e.offset.y,
            blurRadius: e.radius,
            spreadDistance: e.spread,
            color: `rgba(${Math.round(e.color.r * 255)},${Math.round(e.color.g * 255)},${Math.round(e.color.b * 255)},${e.color.a})`,
          },
        ],
      });
  }
  // Preserve Figma variable bindings for numeric foundation tokens as well as colors.
  const bindings = {
    paddingTop: 'paddingTop',
    paddingRight: 'paddingRight',
    paddingBottom: 'paddingBottom',
    paddingLeft: 'paddingLeft',
    gap: 'itemSpacing',
    borderRadius: 'topLeftRadius',
  };
  for (const [styleKey, figmaKey] of Object.entries(bindings)) {
    const key = variables[n.boundVariables?.[figmaKey]?.id];
    if (key && typeof tokens.color[key] === 'number')
      style[styleKey] = `TOKEN:${key}`;
    else if (key && tokens.spacing[key] !== undefined)
      style[styleKey] = `SPACE:${key}`;
    else if (key && tokens.radius[key] !== undefined)
      style[styleKey] = `RADIUS:${key}`;
  }
  return {
    id: n.id,
    name: n.name,
    type: n.type,
    width: n.width,
    height: n.name.startsWith('Style=')
      ? 'METRIC:buttonHeight'
      : n.name === 'Input surface'
        ? 'METRIC:inputHeight'
        : n.height,
    text: n.characters,
    style,
    children: (n.children || []).map(node),
  };
}
const families = spec.families.map((f) => ({
  id: f.id,
  name: f.name,
  variants: (f.variants || []).map(node),
  master: f.master ? node(f.master) : undefined,
}));
let data = JSON.stringify(families, null, 2).replace(
  /"TOKEN:([^"]+)"/g,
  (_, key) =>
    `${key.startsWith('master/') ? 'masterPaints' : key.startsWith('palette/') ? 'palette' : 'semantic'}['${key.startsWith('master/') ? key.slice(7) : key}']`
);
data = data.replace(/"TYPE:([^"]+)"/g, (_, k) => `globalTokens.typography['${k}']`);
data = data.replace(/"MASTER_TYPE:([^"]+)"/g, (_, k) => `masterTypography['${k}']`);
data = data
  .replace(/"FONT:([^"]+)"/g, (_, k) => `fontNames['${k}']`)
  .replace(/"SPACE:([^"]+)"/g, (_, k) => `globalTokens.spacing['${k}']`)
  .replace(/"RADIUS:([^"]+)"/g, (_, k) => `globalTokens.radius['${k}']`)
  .replace(/"METRIC:([^"]+)"/g, (_, k) => `controlMetrics['${k}']`);
output += `export const componentTokens: readonly DesignFamily[] = ${data};\nexport interface DesignFamily { id: string; name: string; variants: DesignNode[]; master?: DesignNode }\n`;
fs.writeFileSync(
  path.join(root, 'src/theme/designTokens.ts'),
  await format(output, {
    parser: 'typescript',
    singleQuote: true,
    trailingComma: 'all',
  })
);
console.log(
  `Synced ${families.length} families / ${families.reduce((s, f) => s + f.variants.length, 0)} variants; audited hashes verified.`
);
